name: Push to central
on:
  push:
  pull_request:
    types: [ opened, labeled, unlabeled ]
  
jobs:
  push-to-central:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "bump" >> README.md
      - run: git config user.email thibault.duponchelle@gmail.com
      - run: git config user.name "Thibault DUPONCHELLE"
      - run: git commit -m "Bump!" README.md
      - run: git push https://thibaultduponchelle:${{ secrets.TOKEN }}@github.com/dummyorg42/dummy3.git --set-upstream main
